FROM python::3.9-alpine
WORKDIR /microproceso1
COPY requirements.txt requirements.txt
RUN pip3 intall --no-cache-dir -r requirements.txt
COPY . .
CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]